---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : twitter
production_url : http://sample.com

posts:
  permalink: /:categories/:filename/
  summary_lines: 5 
  latest: 5 

pages:
  permalink: 'pretty'
