title : 紙飛機
tagline: Blog Tagline
author :
  name : JunQi Lee
  email : jql.buaa@gmail.com
  github : paperplane
  twitter : ipaperplane

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - documentation/fabric/index.md
  - documentation/mcollective/index.md  
  - about.md
